name: SmokePlugin
version: '${project.version}'
main: io.github.kosssst.smoke.SmokePlugin
api-version: 1.20
commands:
  hookah:
    description: Create hookah from brewing stand
    usage: /<command>
